# Generated by Django 4.2.11 on 2024-04-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunch_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MainLunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('content_20_korean_menu', models.TextField()),
                ('content_20_special_menu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubLunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('content_10_lunchbox_menu', models.TextField()),
                ('content_10_sandwich_menu', models.TextField()),
                ('content_10_salad_menu', models.TextField()),
            ],
        ),
    ]
